name: CI
on:
  release:
    types:
      - published
jobs:
  trigger-external-workflow: 
    runs-on: ubuntu-latest
    steps:
      - run: echo "Started Workflow"
      - name: Print Event Object
        run: echo '${{ toJson(github) }}'
      - run: | 
         version=$(echo $GITHUB_REF | sed 's/refs\/tags\///')
         curl -L \
           -X POST \
           -H "Accept: application/vnd.github+json" \
           -H "Authorization: token ${{ secrets.MY_PAT }}"\
             https://api.github.com/repos/shomabegoo/GithubActionWebhookExample/dispatches \
             -d '{
                "event_type":"update-docs",
                "client_payload":{
                  "package_name":"@zio.dev/zio-constraintless", 
                  "package_version": "v0.3.1"
                }
             }'
