name: CI
on:
  push: {}
jobs:
  trigger-external-workflow: 
    permissions: read-all|write-all
    runs-on: ubuntu-latest
    steps:
      - run: echo "Started Workflow"
      - run: | 
         curl -L \
           -X POST \
           -H "Accept: application/vnd.github+json" \
           -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"\
           -H "X-GitHub-Api-Version: 2022-11-28" \
             https://api.github.com/repos/khajavi/GithubActionWebhookExample/dispatches \
             -d '{"event_type":"update-docs","client_payload":{"project":"github-action-webhook-trigger"}}'
