name: CI
on:
  push:
    branches:
      - '**'  # This will trigger on all branches
  release:
    types:
      - published
jobs:
  trigger-external-workflow:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - run: echo "Started Workflow"
      - name: Print Event Object
        run: echo '${{ toJson(github) }}'
#      - name: Generate Token
#        id: generate-token
#        uses: zio/generate-github-app-token@v1.0.0
#        with:
#          app_id: ${{ secrets.APP_ID }}
#          app_private_key: ${{ secrets.APP_SECRET }}
      - name: Generate a token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_SECRET }}
          # Set the owner, so the token can be used in all repositories
          owner: ${{ github.repository_owner }}
      - name: "dispatch"
        run: | 
         version=$(echo $GITHUB_REF | sed 's/refs\/tags\///')
         curl -L \
           -X POST \
           -H "Accept: application/vnd.github+json" \
           -H "Authorization: token ${{ steps.generate-token.outputs.token }}"\
             https://api.github.com/repos/shomabegoo/GithubActionWebhookExample/dispatches \
             -d '{
                "event_type":"update-docs",
                "client_payload":{
                  "package_name":"@zio.dev/zio-constraintless", 
                  "package_version": "v0.3.1"
                }
             }'
