name: CI
on:
  release:
    types:
      - published
jobs:
  trigger-external-workflow: 
    runs-on: ubuntu-latest
    steps:
      - run: echo "Started Workflow"
      - name: Print Event Object
        run: echo '${{ toJson(github) }}'
      - run: | 
         version=$(echo $GITHUB_REF | sed 's/refs\/tags\///')
         curl -L \
           -X POST \
           -H "Accept: application/vnd.github+json" \
           -H "Authorization: Bearer ${{ secrets.PAT }}"\
             https://api.github.com/repos/khajavi/GithubActionWebhookExample/dispatches \
             -d '{
                "event_type":"update-docs",
                "client_payload":{
                  "project":"github-action-webhook-trigger", 
                  "version": "'"${version}"'"
                }
             }'
